services:
  # Run the faucet
  faucet:
    build: .
    image: eth-faucet
    command:
      - -httpport=8180
      - -proxycount=1
      - -faucet.name=nexera
      - -faucet.symbol=NXRA
      - -wallet.provider=${NODE_ENDPOINT:-http://geth:8545}
      - -wallet.privkey=${FAUCET_PK}
    ports:
      - 8180:8180
